apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-bd1o
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/my-app-4/devfile-sample-go-basic-bd1o@sha256:04d21920b2af4ae30db7a609e487f1d1533572b43cdba5b5f7ce8756cfb97135
        name: my-go
        resources: {}
status: {}
