apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-bd1o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-bd1o
    app.kubernetes.io/part-of: my-app-4
  name: devfile-sample-go-basic-bd1o
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-bd1o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-bd1o
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/my-app-4/devfile-sample-go-basic-bd1o@sha256:9eadee6f766c50777f4870399f408f4b5f9b31d967391a31419df8db35f87881
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
