apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-bd1o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-bd1o
    app.kubernetes.io/part-of: my-app-4
  name: devfile-sample-go-basic-bd1o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-bd1o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-bd1o
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/my-app-4/devfile-sample-go-basic-bd1o@sha256:04d21920b2af4ae30db7a609e487f1d1533572b43cdba5b5f7ce8756cfb97135
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
